### ISSUE TITLE
Decomissioning AWS Dx Cluster

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/kafka-pipe-service#3]
`:latest` should probably actually seek to the latest. Maybe `:group` could be the flag for the existing behavior where it doesn't modify the offset from the consumer group.

https://github.com/clingen-data-model/kafka-pipe-service/blob/b0a9ba1345c9ae276eea35c6c7789aeab386c8f9/src/kafka_tools/kafka_pipe_service/core.clj#L21

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: 
Changed name from _Expand offset resetting functionality_ to _Decomissioning AWS Dx Cluster_ 

Notes: Stanford needs to move GV producers over. This ticket can be archived if we get Stanford to finish the decomissioning.

**Comment by KelseaChang5** [comment]
Awaiting status update on this from Matt Wright

**Comment by KelseaChang5** [comment]
Followed up with Matt on Thursday, My 12th

**Comment by dazzariti** [comment]
Danielle asked Matt Wright for an updated June 14

**Comment by larrybabb** [comment]
Hey Matt "Gloria and Bryan should be aware of the AWS Cluster that has an instance of Kafka running on it. We would like to have that all moved over to the formal Confluent Data Exchange server. Can we please setup a time to get this taken care of. This will save $$$ for ClinGen (Stanford primarily). And it will reduce technical debt in terms of us having to manage two kafka clusters."

**Comment by dazzariti** [comment]
Update from Matt: 

Sorry Danielle.. I asked Karen to reach out you last week, but I know she's been swamped… setting up a meeting is a good idea. Maybe we could use the data model slot on Tuesdays since we know we're all available at that time?

**Comment by larrybabb** [comment]
@hdziadzio  and @dazzariti that sounds great. Since we moved the regularly scheduled bi-weekly DM mtg from Jun28 to Jun21 and since the next scheduled meeting in on Jul12 (which I will be traveling on). Maybe we can set up a one off meeting with Kyle/Tristan and Karen/Bryan for 15-30m as soon as is reasonably possible. This should be a minor issue but it will be best communicated and planned with a quick zoom mtg. And include Matt too, pls

**Comment by hdziadzio** [comment]
@larrybabb Sounds good, I'll work on getting something scheduled.

**Comment by hdziadzio** [comment]
Update: Larry/Tristan/Kyle met with Matt/Gloria/Bryan on 7/6 to discuss the plan.

Action items:

- Stanford team will discuss further to determine how big a task this will be, then inform B/G team of timeframe (will consider a small patch release).
- Stanford team will review list (https://github.com/clingen-data-model/data-exchange-migration/blob/master/src/data_exchange_migration/core.clj#L125-L135), track down where they are producing to, switch to producing messages onto Dx server.
- Stanford team will reach out to Kyle/Tristan to get info on new connection (Kyle needs to grant write permissions)

**Comment by larrybabb** [comment]
Here's the issue on the VCI/GCI github issue board ... https://github.com/ClinGen/gene-and-variant-curation-tools/issues/223

**Comment by dazzariti** [comment]
Larry talked to Matt Wright about this Aug 5th - Stanford team is delayed but this is on their radar to complete by the end of September.
